# Generated by Django 2.2.5 on 2022-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
