# Generated by Django 3.1.5 on 2022-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_services_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='team',
            name='age',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sex',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=40, verbose_name='BLog Title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Team Member Name'),
        ),
    ]
