# Generated by Django 2.2.5 on 2022-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Type',
            field=models.CharField(max_length=20),
        ),
    ]
