# Generated by Django 2.2.5 on 2022-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20220413_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/pics')),
                ('Type', models.CharField(max_length=20)),
                ('discription', models.TextField()),
            ],
        ),
    ]
