# Generated by Django 2.2.5 on 2022-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='discription',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Type',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='Address',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
