# Generated by Django 2.2.5 on 2022-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20220413_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Contact',
            field=models.CharField(max_length=20),
        ),
    ]
