# Generated by Django 2.2.5 on 2022-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20220413_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
